### ISSUE TITLE
Provide a standalone binary executable.

### ISSUE THREAD

**Issue by GamePlayer-8** [blackdragon2447/riscv_vm#1]
Heya,

Is your software going to have a CI/CD what would build a standalone binary for simple usage?

**Comment by blackdragon2447** [comment]
I added workflows for building, see: https://github.com/blackdragon2447/riscv_vm/actions/runs/7814951645, there are two artifacts, both are the emulator but the _vga one has the vga device enabled and attached to the vm, it is build separately because of size (2MB vs 37MB), gonna leave this issue open for a bit as a reminder that I also need to setup test workflows.

**Comment by blackdragon2447** [comment]
Whatever os or similar you wanna run of the vm needs to be an elf file.
If you have a look in `vm_tests/custom_tests` you can see how the custom tests are build from assembly into elf files which are runnable on the vm (c can be built for the vm in a similar way).

**Comment by blackdragon2447** [comment]
There now is an example elf file in the artifacts both do nothing but say hello but they should work.
